// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/gg_bridge_dart_typescript_version.test.ts.

/** The version of the `@tssuite/gg-bridge-dart-typescript` package. */
export const ggBridgeDartTypescriptVersion = '1.0.2';
